### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by dusankaPrvulovic** [cmda-bt/js-bootcamp-18-19#4] opened 2019-02-04 15:29 UTC
# Exercises

## Name
Dusanka Prvulovic

## Class
204

## GitHub username
https://github.com/dusankaPrvulovic/

## Bootcamp exercises
Fizzbuzz: https://github.com/dusankaPrvulovic/js-bootcamp/blob/master/l1-fizzbuzz.js

Looping a triangle: https://github.com/dusankaPrvulovic/js-bootcamp/blob/master/l1-looping-a-triangle.js

## Bootcamp notes
https://github.com/dusankaPrvulovic/js-bootcamp/blob/master/notes.md

**Comment by dandevri** [comment] 2019-02-04 16:34
Duplicate of #3

**Closed as completed by dandevri** 2019-02-04 16:34 UTC
Labels: tech-2, week-1, week-1-exercises
