### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by charder001** [cmda-bt/js-bootcamp-18-19#99] opened 2019-04-22 12:34 UTC
# Exercises

## Name
Rick Chardet

## Class
Tech3

## GitHub username
Charder001

## Bootcamp exercises
https://github.com/charder001/js-bootcamp

## Bootcamp notes
https://github.com/charder001/js-bootcamp/blob/master/notes.md

**Comment by dandevri** [comment] 2019-05-05 11:54
Duplicate of #152

**Closed as completed by dandevri** 2019-05-05 11:54 UTC
Labels: tech-3, on-time:yes, week-2, week-2-exercises
