### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by robert-hoekstra** [cmda-bt/js-bootcamp-18-19#120] opened 2019-04-24 18:41 UTC
# My Introduction

## Name
Robert Hoekstra

## Class
214 (Tech3)

## About me
I want to become a UX-Designer

## Goals
Having a better understanding of JavaScript and being able to write and think like code.

## Skill level
Beginner

## GitHub username
robert-hoekstra

## GitHub repository
https://github.com/robert-hoekstra/js-bootcamp

**Comment by dandevri** [comment] 2019-05-05 10:23
Duplicate of #104

**Closed as completed by dandevri** 2019-05-05 10:23 UTC
Labels: tech-3, week-0-repository
